version: 2

project_name: kubehatch

release:
  github:
    owner: LoftLabs-Experiments
    name: kubehatch

builds:
  - id: backend
    dir: backend
    main: ./main.go
    binary: kubehatch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: backend_archive
    builds:
      - backend
    format: tar.gz
    files:
      - frontend/index.html
      - frontend/*  # ✅ Ensures all frontend files are included

checksum:
  name_template: "checksums.txt"

