
project_name: kubehatch

release:
  github:
    owner: LoftLabs-Experiments
    name: kubehatch

builds:
  - id: backend
    dir: backend
    main: ./main.go
    binary: kubehatch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: backend_archive
    builds:
      - backend
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

dockers:  # ✅ FIXED: Correct key is 'dockers', not 'docker'
  - image_templates:
      - "ghcr.io/loftlabs-experiments/kubehatch-backend:{{ .Tag }}"
    dockerfile: backend/Dockerfile.backend
    build_flag_templates:
      - "--platform=linux/amd64"
    use: "buildx"
    skip_push: false

  - image_templates:
      - "ghcr.io/loftlabs-experiments/kubehatch-frontend:{{ .Tag }}"
    dockerfile: frontend/Dockerfile.frontend
    build_flag_templates:
      - "--platform=linux/amd64"
    use: "buildx"
    skip_push: false
