version: 2

project_name: kubehatch

release:
  github:
    owner: LoftLabs-Experiments
    name: kubehatch

builds:
  - id: backend
    dir: backend
    main: ./main.go
    binary: kubehatch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - "ghcr.io/loftlabs-experiments/kubehatch-backend:{{ .Tag }}"
      - "ghcr.io/loftlabs-experiments/kubehatch-backend:latest"
    dockerfile: backend/Dockerfile.backend
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
    skip_push: false

  - image_templates:
      - "ghcr.io/loftlabs-experiments/kubehatch-frontend:{{ .Tag }}"
      - "ghcr.io/loftlabs-experiments/kubehatch-frontend:latest"
    dockerfile: frontend/Dockerfile.frontend
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
    skip_push: false
