# .goreleaser.yaml
version: 2

project_name: kubehatch

monorepo:
  tag_prefix: kubehatch/

release:
  github:
    owner: LoftLabs-Experiments
    name: kubehatch

builds:
  - id: backend
    dir: backend
    main: ./main.go
    binary: kubehatch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: backend_archive
    builds:
      - backend
    format: tar.gz
    replacements:
      darwin: macOS
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

docker:
  - id: backend_docker
    image_templates:
      - "yourdockerregistry/kubehatch-backend:{{ .Tag }}"
    dockerfile: backend/Dockerfile.backend
    build_flag_templates:
      - "--platform=linux/amd64"
    skip_push: false
  - id: frontend_docker
    image_templates:
      - "yourdockerregistry/kubehatch-frontend:{{ .Tag }}"
    dockerfile: frontend/Dockerfile.frontend
    build_flag_templates:
      - "--platform=linux/amd64"
    skip_push: false
