version: 2
project_name: kubehatch

builds:
  - id: kubehatch-backend
    main: ./backend/main.go
    binary: kubehatch
    goos:
      - linux
      - darwin
      - windows

dockers:
  - image_templates:
      - "ghcr.io/loftlabs-experiments/kubehatch:{{ .Version }}"
    dockerfile: backend/Dockerfile.backend
    builds:
      - backend

builds:
  - id: backend
    main: backend/main.go
    binary: kubehatch-backend
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: tar.gz
    builds:
      - backend
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: amd64
      arm64: arm64

release:
  github:
    owner: LoftLabs-Experiments
    name: kubehatch
