site_name: KubeHatch CLI
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: cyan
nav:
  - Home: index.md
  - Quickstart: QUICKSTART.md
  - Build from Source: BUILD.md

repo_url: https://github.com/LoftLabs-Experiments/kubehatch
repo_name: LoftLabs-Experiments/kubehatch

site_dir: site

