version: 2

project_name: kubehatch

release:
  github:
    owner: LoftLabs-Experiments
    name: kubehatch

builds:
  - id: backend
    main: ./main.go  # /kubehatch/backend/main.go
    binary: kubehatch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: backend_archive
    builds:
      - backend
    format: tar.gz
    files:
      - ../frontend/index.html  # Should resolve to /kubehatch/frontend/index.html

checksum:
  name_template: "checksums.txt"

dockers:
  - image_templates:
      - "ghcr.io/loftlabs-experiments/kubehatch-backend:{{ .Tag }}"
      - "ghcr.io/loftlabs-experiments/kubehatch-backend:latest"
    dockerfile: Dockerfile.backend  # /kubehatch/backend/Dockerfile.backend
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
    skip_push: false
    extra_files:
      - ../frontend/index.html  # /kubehatch/frontend/index.html

  - image_templates:
      - "ghcr.io/loftlabs-experiments/kubehatch-frontend:{{ .Tag }}"
      - "ghcr.io/loftlabs-experiments/kubehatch-frontend:latest"
    dockerfile: ../frontend/Dockerfile.frontend  # /kubehatch/frontend/Dockerfile.frontend
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
    skip_push: false
    extra_files:
      - ../frontend/index.html  # /kubehatch/frontend/index.html
