name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Manually build and push Docker images
      - name: Build & Push Backend Image
        run: |
          docker build -t ghcr.io/loftlabs-experiments/kubehatch-backend:${{ github.ref_name }} -t ghcr.io/loftlabs-experiments/kubehatch-backend:latest -f backend/Dockerfile.backend backend/
          docker push ghcr.io/loftlabs-experiments/kubehatch-backend:${{ github.ref_name }}
          docker push ghcr.io/loftlabs-experiments/kubehatch-backend:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t ghcr.io/loftlabs-experiments/kubehatch-frontend:${{ github.ref_name }} -t ghcr.io/loftlabs-experiments/kubehatch-frontend:latest -f frontend/Dockerfile.frontend frontend/
          docker push ghcr.io/loftlabs-experiments/kubehatch-frontend:${{ github.ref_name }}
          docker push ghcr.io/loftlabs-experiments/kubehatch-frontend:latest

