version: '2'

project_name: kubehatch

release:
  github:
    owner: LoftLabs-Experiments
    name: kubehatch

builds:
  - main: ./backend/main.go
    binary: kubehatch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - "LoftLabs-Experiments/kubehatch-backend:{{ .Tag }}"
    dockerfile: backend/Dockerfile.backend
    build_flag_templates:
      - "--platform=linux/amd64"
    skip_push: false
